### ISSUE TITLE
Warning during `make` on debian

### ISSUE THREAD

**Issue by jonatack** [chaincodelabs/libmultiprocess#39]
I was able to build manually but did see this warning during make, if helpful.

- capnproto 0.7.0-7
- debian 5.8.10-1 (2020-09-19) x86_64 GNU/Linux
- gcc (Debian 10.2.0-9) 10.2.0

```make
/libmultiprocess/src/mp/gen.cpp: In function ‘void Generate(kj::StringPtr, kj::StringPtr, kj::StringPtr, kj::ArrayPtr<const kj::StringPtr>)’:
/libmultiprocess/src/mp/gen.cpp:164:77: warning: ‘capnp::ParsedSchema capnp::SchemaParser::parseDiskFile(kj::StringPtr, kj::StringPtr, kj::ArrayPtr<const kj::StringPtr>) const’ is deprecated [-Wdeprecated-declarations]
  164 |     auto file_schema = parser.parseDiskFile(src_file, src_file, import_paths);
      |                                                                             ^
In file included from /libmultiprocess/src/mp/gen.cpp:9:
/usr/include/capnp/schema-parser.h:103:16: note: declared here
  103 |   ParsedSchema parseDiskFile(kj::StringPtr displayName, kj::StringPtr diskPath,
      |                ^~~~~~~~~~~~~
```

**Comment by jonatack** [comment]
Just saw this again now while building manually.

**Comment by ryanofsky** [comment]
Thanks, it's been kind of a low priority to fix this warning since the code does work and keeping it makes it easy to retain compatibility with older versions of capnproto. But this should really update to a non-deprecated call.

**Comment by promag** [comment]
I tried to ditch those warnings and it's not a plain change, needs a bit of refactor so I've decided to avoid it while getting comfortable with the code base.
